LDFLAGS += -L/home/hbn/Documents/AIMS/projet/master/github/modular_independent_sub5/framework_build
LDFLAGS += -L/home/hbn/Documents/AIMS/projet/master/github/modular_independent_sub5/framework_build/src/util-generic
LDFLAGS += -Wl,-rpath='$$ORIGIN'
LDFLAGS += -Wl,-rpath='/home/hbn/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.4.0/gpi-space-22.09-c2fwsd6d7pug6g5qtsxnsrtj4krunlke/lib'
LDFLAGS += -Wl,-rpath='/home/hbn/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.4.0/gpi-space-22.09-c2fwsd6d7pug6g5qtsxnsrtj4krunlke/external/boost/lib'
