CXXFLAGS += -O3
CXXFLAGS += -std=c++17
CXXFLAGS += -I/home/hbn/Documents/AIMS/projet/master/github/modular_independent_sub5/framework_build
CXXFLAGS += -I/home/hbn/Documents/AIMS/projet/master/github/modular_independent_sub5
CXXFLAGS += -I/home/hbn/Documents/AIMS/projet/master/github/modular_independent_sub5/src
CXXFLAGS += -I/home/hbn/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.4.0/gpi-space-22.09-c2fwsd6d7pug6g5qtsxnsrtj4krunlke/include
CXXFLAGS += -I/home/hbn/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.4.0/gpi-space-22.09-c2fwsd6d7pug6g5qtsxnsrtj4krunlke/external/boost/include
